import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Prakhar Rai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="content">

        <p>This is the site of <b>Prakhar Rai</b>, developer, engineer & tinkerer.</p>

        <p>I've completed my B.Tech in <em>Computer Science Engineering</em> in 2023. <br /><br /> I've previously worked with Cisco and Interview Kickstart as an intern. I'm currently working at a unicorn Physics Wallah where I'm leading the backend team of <em>Nugget-o-verse.</em></p>

        <ul class="index">
          <li><span class="index-date">∞</span><a href="/blogs">Blogs</a></li>
          <li><span class="index-date">∞</span><a href="/about">About me</a></li>
          <li><span class="index-date">∞</span><a href="/contact">Contact</a></li>
        </ul>
      </div>
    </>
  )
}
